version: '3.8'

services: 
    db:
        #user is required using a Linux OS
        #user: $UID
        image: mysql
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: podify
            MYSQL_USER: pody-admin
            MYSQL_PASSWORD: 3aNz3Ly4pFTNf9bS
            MYSQL_ROOT_PASSWORD: 3aNz3Ly4pFTNf9bS
        expose:
            - 3306
        volumes:
            - ./data/db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    cache:
        image: redis:alpine
        ports: 
            - '6379:6379'
        command: ['--requirepass "Nt4VzWPtDhkCxESjXVJx"']